max steps: 100
delta t: 3600      # Seconds
start t: 2019/01/01 15:00:01
end t: 2019/01/08 15:00:00

city: data/chicago-map.pkl
demand: data/chicago_demand.csv

enable_v2g: False # V1G Baseline

fleet:
  size: 50
  vehicle: BYD E6
  battery model: multistage
  depot: none

charging stations:
  - location: 76
    max port power: 10
    max total power: 500
    efficiency: 0.9
    ports: 10
  - location: 55
    max port power: 50
    max total power: 500
    efficiency: 0.9
    ports: 10
