max steps: 100
delta t: 3600      # Seconds
start t: 2023/01/01 00:00:00
end t: 2023/01/07 23:59:59

city: data/chicago-map.pkl
demand: data/chicago_demand.csv

enable_v2g: True # V2G Enabled

fleet:
  size: 50
  vehicle: BYD E6
  battery model: multistage
  depot: none

charging stations:
  - location: 76
    max port power: 10
    max total power: 500
    efficiency: 0.9
    ports: 10
  - location: 55
    max port power: 50
    max total power: 500
    efficiency: 0.9
    ports: 10
